services:
  mongo:
    image: mongo:7
    container_name: projectm-mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: projectm
      MONGO_INITDB_ROOT_PASSWORD: projectm
      MONGO_INITDB_DATABASE: projectm
    volumes:
      - mongo_data:/data/db

  rabbitmq:
    image: rabbitmq:3-management
    container_name: projectm-rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: projectm
      RABBITMQ_DEFAULT_PASS: projectm
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

  minio:
    image: minio/minio:latest
    container_name: projectm-minio
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: projectm
      MINIO_ROOT_PASSWORD: projectm123
    volumes:
      - minio_data:/data

volumes:
  mongo_data:
  rabbitmq_data:
  minio_data: