services:
  postgres:
    image: postgres:17-alpine
    container_name: projectm-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1
      POSTGRES_DB: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d postgres" ]
      interval: 5s
      timeout: 3s
      retries: 10

  mongo:
    image: mongo:7
    container_name: projectm-mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: projectm
      MONGO_INITDB_ROOT_PASSWORD: projectm
      MONGO_INITDB_DATABASE: projectm
    volumes:
      - mongo_data:/data/db

  redis:
    image: redis:7-alpine
    container_name: projectm-redis
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data

  rabbitmq:
    image: rabbitmq:3-management
    container_name: projectm-rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: projectm
      RABBITMQ_DEFAULT_PASS: projectm
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

  minio:
    image: minio/minio:latest
    container_name: projectm-minio
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: projectm
      MINIO_ROOT_PASSWORD: projectm123
    volumes:
      - minio_data:/data

volumes:
  postgres_data:
  mongo_data:
  redis_data:
  rabbitmq_data:
  minio_data:
