spring:
  mail:
    host: ${MAILTRAP_HOST:sandbox.smtp.mailtrap.io}
    port: ${MAILTRAP_PORT:2525}
    username: ${MAILTRAP_USERNAME}
    password: ${MAILTRAP_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

app:
  mail:
    from: ${APP_MAIL_FROM:ProjectM Local <no-reply@projectm.test>}
    verification-url: ${APP_VERIFICATION_URL:http://localhost:8080/api/v1/auth/verify}
    password-reset-url: ${APP_VERIFICATION_URL:http://localhost:8080/api/v1/auth/reset-password}