spring:
  application:
    name: projectM

  config:
    import: "optional:file:.env[.properties]"

  profiles:
    active: ${SPRING_PROFILES_ACTIVE:local}

  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/postgres?currentSchema=public}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:1}
    driver-class-name: org.postgresql.Driver

  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      database: ${REDIS_DATABASE:0}
    mongodb:
      auto-index-creation: true

  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    properties:
      hibernate:
        format-sql: true
        default-schema: ${DB_SCHEMA:public}

  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yaml
  mongodb:
    uri: ${MONGODB_URI:mongodb://projectm:projectm@localhost:27017/projectm?authSource=admin}
    uuid-representation: standard

  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USERNAME:projectm}
    password: ${RABBITMQ_PASSWORD:projectm}
    publisher-confirm-type: correlated

app:
  mail:
    from: ${APP_MAIL_FROM:no-reply@projectm.local}
    verification-url: ${APP_VERIFICATION_URL:http://localhost:8080/api/v1/auth/verify}
    password-reset-url: ${APP_VERIFICATION_URL:http://localhost:8080/api/v1/auth/reset-password}
  cors:
    allowed-origins: ${APP_CORS_ALLOWED_ORIGINS:http://localhost:5173}
  jwt:
    secret: ${JWT_TOKEN_SECRET}